sudo: required
services:
    - docker

before_install:
    - docker build -t jangdonghyeon/react-test -f Dockerfile.dev .

script:
    - docker run -e CI=true jangdonghyeon/react-test npm run test

after_success:
    - docker build -t jangdonghyeon/multi-client ./client
    - docker build -t jangdonghyeon/multi-nginx ./nginx
    - docker build -t jangdonghyeon/multi-server ./server
    - docker build -t jangdonghyeon/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jangdonghyeon/multi-client
    - docker push jangdonghyeon/multi-nginx
    - docker push jangdonghyeon/multi-server
    - docker push jangdonghyeon/multi-worker
